name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      aws_session_token:
        description: 'AWS Session Token'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ github.event.inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.aws_secret_access_key }}
      AWS_SESSION_TOKEN: ${{ github.event.inputs.aws_session_token }}

    defaults:
      run:
        working-directory: iac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
